Povoamento de Dados- Dimensão Instrutor

Importação de Pacotes

In [3]:
import pandas as pd

Leitura de Dados da fonte

In [4]:
instrutores = pd.read_csv('../Fontes/instrutores_ginasio_fonte.csv', encoding='latin1')
print(f"Registos lidos: {instrutores.shape[0]}")
display(instrutores.head())

Registos lidos: 10

,id_instrutor,nome,data_nascimento,competencias_academicas,area_especializacao
0,1,Enzo Pacheco,12/5/1986,Mestrado em Exercício e Saúde,Musculação
1,2,Anita Antunes,1/21/1988,Mestrado em Desporto,Yoga
2,3,Pilar Cruz,12/2/1996,Curso Técnico de Exercício Físico,Zumba
3,4,Sara Neto,5/27/1966,Licenciatura em Educação Física,Cardio
4,5,Sérgio Pires,6/12/1993,Licenciatura em Ciências do Desporto,Pilates

Validação da Integridade

In [5]:
print("Duplicados no ID:", instrutores.duplicated(subset=['id_instrutor']).sum())
print("Valores nulos por coluna:\n", instrutores.isnull().sum())

# Garantir unicidade e integridade mínima
assert instrutores['id_instrutor'].is_unique, "IDs de instrutor não são únicos!"
assert instrutores[['id_instrutor', 'nome', 'area_especializacao']].isnull().sum().sum() == 0, "Existem valores críticos em falta!"

Duplicados no ID: 0
Valores nulos por coluna:
 id_instrutor               0
nome                       0
data_nascimento            0
competencias_academicas    0
area_especializacao        0
dtype: int64

Seleção e Transformação dos Campos

In [6]:
dim_instrutor = instrutores[['id_instrutor', 'nome', 'area_especializacao']].copy()

# Renomear colunas para consistência dimensional
dim_instrutor = dim_instrutor.rename(columns={
    'id_instrutor': 'instrutor_id',
    'nome': 'instrutor_nome',
    'area_especializacao': 'instrutor_especializacao'
})

Gerar Surrogate Key

In [7]:
dim_instrutor.insert(1, 'instrutor_sk', range(1, 1 + len(dim_instrutor)))

Exportação dos Dados

In [8]:
dim_instrutor.to_csv("../Dados Finais/dim_instrutor.csv", index=False, encoding="utf-8-sig")
print("Dimensão Instrutor pronta para carga.")
display(dim_instrutor.head())

Dimensão Instrutor pronta para carga.

   instrutor_id  instrutor_sk instrutor_nome instrutor_especializacao
0             1             1   Enzo Pacheco               Musculação
1             2             2  Anita Antunes                     Yoga
2             3             3     Pilar Cruz                    Zumba
3             4             4      Sara Neto                   Cardio
4             5             5   Sérgio Pires                  Pilates