Povoamento de Dados- Dimensão Tipo de Aula

Importação de Pacotes

In [1]:
import pandas as pd

Leitura das Fontes de Dados

In [2]:
atividades = pd.read_csv('../Fontes/atividades_ginasio_fonte.csv', encoding='latin1')
print(f"Registos de atividades lidos: {atividades.shape[0]}")
atividades.head()

Registos de atividades lidos: 30

,id_atividade,tipo_atividade,nome_atividade,duracao_minutos,calorias_medias_queimadas,nivel_dificuldade,nivel_intensidade,objetivo_treino
0,1,Aula de grupo,Aula de Alongamentos,36,548,Alto,Alta,Relaxamento
1,2,Aula de grupo,Aula de Boxe,58,220,Alto,Média,Flexibilidade
2,3,Aula de grupo,Aula de Cardio,52,530,Alto,Baixa,Resistência
3,4,Aula de grupo,Aula de Crossfit,37,351,Alto,Média,Bem-estar
4,5,Aula de grupo,Aula de Funcional,31,543,Médio,Média,Ganho de massa

Filtração das Atividades por apenas Aulas de Grupo

In [3]:
aulas = atividades[atividades['tipo_atividade'].str.strip().str.lower() == 'aula de grupo'].copy()
print(f"Aulas identificadas: {aulas.shape[0]}")

Aulas identificadas: 10

Verificação da Integridade dos Dados

In [4]:
assert aulas['id_atividade'].is_unique, "IDs de treino não são únicos!"
assert aulas[['nome_atividade', 'duracao_minutos', 'calorias_medias_queimadas', 'objetivo_treino', 'nivel_intensidade']].isnull().sum().sum() == 0, "Existem valores críticos em falta!"

Adicionar elemento de Capacidade

In [5]:
aulas["capacidade"] = 40

Seleção dos Atributos

In [6]:
dim_aulas = aulas[[
    'id_atividade', 'nome_atividade', 'duracao_minutos', 'calorias_medias_queimadas',
    'nivel_intensidade', 'capacidade'
]].copy()

dim_aulas = dim_aulas.rename(columns={
    'id_atividade': 'aula_id',
    'nome_atividade': 'aula_nome',
    'duracao_minutos': 'aula_duracao_min',
    'calorias_medias_queimadas': 'aula_calorias', 
    'nivel_intensidade': 'aula_intensidade',
    'capacidade': 'aula_capacidade',
})

Gerar Surrogate Key

In [7]:
dim_aulas.insert(1, 'aula_sk', range(1, 1 + len(dim_aulas)))

Exportação dos Dados

In [8]:
dim_aulas.to_csv("../Dados Finais/dim_aula.csv", index=False, encoding="utf-8-sig")
print("Dimensão Tipo De Aula pronta para carga!")
dim_aulas.head()

Dimensão Tipo De Aula pronta para carga!

,aula_id,aula_sk,aula_nome,aula_duracao_min,aula_calorias,aula_intensidade,aula_capacidade
0,1,1,Aula de Alongamentos,36,548,Alta,40
1,2,2,Aula de Boxe,58,220,Média,40
2,3,3,Aula de Cardio,52,530,Baixa,40
3,4,4,Aula de Crossfit,37,351,Média,40
4,5,5,Aula de Funcional,31,543,Média,40